namespace Ama.Enterprise.P2p.WebRTC.AspNetCore.Extensions;

using System;
using System.IO;
using Ama.CRDT.Services.Serialization;
using Ama.Enterprise.P2p.WebRTC.Models;
using Ama.Enterprise.P2p.WebRTC.Services;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

/// <summary>
/// Provides extension methods for mapping ASP.NET Core API endpoints resolving out-of-band WebRTC signaling streams.
/// </summary>
public static class EndpointRouteBuilderExtensions
{
    /// <summary>
    /// Maps standard inbound WebRTC signaling endpoints managing HTTP isolated handshakes negotiating SDP descriptors.
    /// </summary>
    /// <param name="endpoints">The route builder instance tracking internal HTTP structural boundaries.</param>
    /// <param name="routePrefix">The base path prefix standardizing explicit routes. Defaults to "/ama-enterprise/webrtc-signaling".</param>
    /// <returns>A convention builder permitting explicit mapped endpoint customization.</returns>
    public static IEndpointConventionBuilder MapP2pWebRtcSignalingEndpoints(this IEndpointRouteBuilder endpoints, string routePrefix = "/ama-enterprise/webrtc-signaling")
    {
        ArgumentNullException.ThrowIfNull(endpoints);

        var group = endpoints.MapGroup(routePrefix.TrimEnd('/'));

        // Generate an offer from this node
        group.MapPost("/{meshId}/offer", new RequestDelegate(async context =>
        {
            var meshId = context.GetRouteValue("meshId")?.ToString();
            if (string.IsNullOrEmpty(meshId))
            {
                context.Response.StatusCode = StatusCodes.Status400BadRequest;
                return;
            }

            var invitationService = context.RequestServices.GetKeyedService<IWebRtcInvitationService>(meshId);
            if (invitationService is null)
            {
                context.Response.StatusCode = StatusCodes.Status404NotFound;
                return;
            }

            var serializer = context.RequestServices.GetRequiredService<ICrdtSerializer>();
            var offer = await invitationService.CreateInvitationAsync(context.RequestAborted).ConfigureAwait(false);

            var responseBytes = serializer.SerializeToBytes(offer);
            context.Response.StatusCode = StatusCodes.Status200OK;
            context.Response.ContentType = "application/json";
            context.Response.ContentLength = responseBytes.Length;
            await context.Response.Body.WriteAsync(responseBytes, context.RequestAborted).ConfigureAwait(false);
        }));

        // Finalize an offer previously generated by this node
        group.MapPost("/{meshId}/finalize", new RequestDelegate(async context =>
        {
            var meshId = context.GetRouteValue("meshId")?.ToString();
            if (string.IsNullOrEmpty(meshId))
            {
                context.Response.StatusCode = StatusCodes.Status400BadRequest;
                return;
            }

            var invitationService = context.RequestServices.GetKeyedService<IWebRtcInvitationService>(meshId);
            if (invitationService is null)
            {
                context.Response.StatusCode = StatusCodes.Status404NotFound;
                return;
            }

            var serializer = context.RequestServices.GetRequiredService<ICrdtSerializer>();
            using var ms = new MemoryStream();
            await context.Request.Body.CopyToAsync(ms, context.RequestAborted).ConfigureAwait(false);

            try
            {
                var answer = serializer.DeserializeFromBytes<WebRtcInvitationAnswer>(ms.ToArray());
                await invitationService.FinalizeInvitationAsync(answer.ConnectionId, answer.SdpAnswer, context.RequestAborted).ConfigureAwait(false);
                context.Response.StatusCode = StatusCodes.Status202Accepted;
            }
            catch (Exception ex)
            {
                var logger = context.RequestServices.GetRequiredService<ILoggerFactory>().CreateLogger(typeof(EndpointRouteBuilderExtensions));
                logger.LogWarning(ex, "[{MeshId}] Failed to finalize explicit WebRTC invitation.", meshId);
                context.Response.StatusCode = StatusCodes.Status400BadRequest;
            }
        }));

        // Receive an offer from a remote node and answer it explicit
        group.MapPost("/{meshId}/answer", new RequestDelegate(async context =>
        {
            var meshId = context.GetRouteValue("meshId")?.ToString();
            if (string.IsNullOrEmpty(meshId))
            {
                context.Response.StatusCode = StatusCodes.Status400BadRequest;
                return;
            }

            var invitationService = context.RequestServices.GetKeyedService<IWebRtcInvitationService>(meshId);
            if (invitationService is null)
            {
                context.Response.StatusCode = StatusCodes.Status404NotFound;
                return;
            }

            var serializer = context.RequestServices.GetRequiredService<ICrdtSerializer>();
            using var ms = new MemoryStream();
            await context.Request.Body.CopyToAsync(ms, context.RequestAborted).ConfigureAwait(false);

            try
            {
                var offer = serializer.DeserializeFromBytes<WebRtcInvitationOffer>(ms.ToArray());
                var answer = await invitationService.AcceptInvitationAsync(offer.SdpOffer, context.RequestAborted).ConfigureAwait(false);

                var responseBytes = serializer.SerializeToBytes(answer);
                context.Response.StatusCode = StatusCodes.Status200OK;
                context.Response.ContentType = "application/json";
                context.Response.ContentLength = responseBytes.Length;
                await context.Response.Body.WriteAsync(responseBytes, context.RequestAborted).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                var logger = context.RequestServices.GetRequiredService<ILoggerFactory>().CreateLogger(typeof(EndpointRouteBuilderExtensions));
                logger.LogWarning(ex, "[{MeshId}] Failed to accept inbound WebRTC SDP offer.", meshId);
                context.Response.StatusCode = StatusCodes.Status400BadRequest;
            }
        }));

        return group;
    }
}