<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<PackageId>Ama.Enterprise.P2p</PackageId>
		<Version>0.0.0</Version>
		<Authors>Alexander Mantzoukas</Authors>
		<Description></Description>
		<RepositoryUrl>https://github.com/phaetto/Ama.Enterprise</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>Proprietary</PackageLicenseExpression>
		<PackageTags>crdt;p2p;gossip;distributed-systems;collaboration;conflict-free</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<!-- SourceLink and Symbol Configuration -->
		<PublishRepositoryUrl>false</PublishRepositoryUrl>
		<EmbedUntrackedSources>false</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!-- Generate XML documentation file -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<!-- Suppress warning for missing comments on internal/private members -->
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Ama.CRDT" Version="3.1.260420-ci1502" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.6" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.6" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ama.Enterprise.Project.Analyzers\Ama.Enterprise.Project.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
