// <auto-generated/>
namespace Ama.Enterprise.CRDT.MessagePack.Analyzers.Generators;

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class MessagePackFormatterGenerator : IIncrementalGenerator
{
    private const string JsonSerializableAttributeFullName = "System.Text.Json.Serialization.JsonSerializableAttribute";

    // Add all known decoupled contexts here so the generator natively reaches into referenced NuGet assemblies 
    // and synthesizes their formatters automatically into the consumer's App resolver.
    private static readonly string[] KnownFrameworkContexts = new[]
    {
        "Ama.CRDT.Models.Serialization.CrdtJsonContext",
        "Ama.Enterprise.P2p.Models.Gossip.P2pJsonSerializerContext",
        "Ama.Enterprise.CRDT.Distributed.Models.DistributedCrdtSystemJsonContext",
        "Ama.Enterprise.FeatureFlags.Models.FeatureFlagsJsonContext",
        "Ama.Enterprise.P2p.AspNetCore.Models.AspNetCoreJsonContext",
        "Ama.Enterprise.P2p.Mqtt.Models.MqttJsonContext",
        "Ama.Enterprise.P2p.Mqtt.Models.MqttDiscoveryJsonContext",
        "Ama.Enterprise.P2p.Telemetry.Models.TelemetryJsonContext",
        "Ama.Enterprise.P2p.WebRTC.Models.WebRtcJsonContext",
        "Ama.Enterprise.CRDT.Distributed.Models.DistributedCrdtP2pJsonContext",
        "Ama.Enterprise.P2p.Services.Discovery.UdpDiscoveryJsonContext",
    };

    private static readonly SymbolDisplayFormat DefinitionFormat = new SymbolDisplayFormat(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var stjAttributes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
                transform: static (ctx, _) => 
                {
                    if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol symbol) return null;
                    
                    var hasAttr = symbol.GetAttributes().Any(a => 
                        a.AttributeClass?.Name == "JsonSerializableAttribute" || 
                        a.AttributeClass?.ToDisplayString() == JsonSerializableAttributeFullName);
                        
                    return hasAttr ? symbol : null;
                })
            .Where(static symbol => symbol is not null);

        var compilationProvider = context.CompilationProvider;

        var combined = stjAttributes.Collect().Combine(compilationProvider);

        context.RegisterSourceOutput(combined, Execute);
    }

    private static void Execute(SourceProductionContext context, (ImmutableArray<INamedTypeSymbol?> SyntaxContexts, Compilation Compilation) source)
    {
        var targetTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        
        // 1. Collect manually specified JsonSerializable attributes in current application's compilation
        foreach (var symbol in source.SyntaxContexts)
        {
            if (symbol == null) continue;
            ExtractTargetTypes(symbol, targetTypes);
        }

        // 2. Automatically map against standard CRDT/P2P STJ contexts referenced via NuGet or Project References
        foreach (var contextName in KnownFrameworkContexts)
        {
            var frameworkContext = source.Compilation.GetTypeByMetadataName(contextName);
            if (frameworkContext != null)
            {
                ExtractTargetTypes(frameworkContext, targetTypes);
            }
        }

        if (targetTypes.Count == 0) return;

        var discoveredCustomTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        var discoveredCollectionTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        
        TraverseTypes(targetTypes, discoveredCustomTypes, discoveredCollectionTypes);

        var assemblyName = source.Compilation.AssemblyName?.Replace(".", "_").Replace("-", "_") ?? "App";
        var resolverName = $"{assemblyName}_MessagePackResolver";

        GenerateResolver(context, discoveredCustomTypes, discoveredCollectionTypes, resolverName);
    }

    private static void ExtractTargetTypes(INamedTypeSymbol contextSymbol, HashSet<ITypeSymbol> targetTypes)
    {
        var attributes = contextSymbol.GetAttributes()
            .Where(a => a.AttributeClass?.Name == "JsonSerializableAttribute" || 
                        a.AttributeClass?.ToDisplayString() == JsonSerializableAttributeFullName);

        foreach (var attr in attributes)
        {
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is ITypeSymbol targetType)
            {
                targetTypes.Add(targetType);
            }
        }
    }

    private static void TraverseTypes(HashSet<ITypeSymbol> rootTypes, HashSet<INamedTypeSymbol> customTypes, HashSet<ITypeSymbol> collectionTypes)
    {
        var visited = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        var queue = new Queue<ITypeSymbol>(rootTypes);

        while (queue.Count > 0)
        {
            var type = queue.Dequeue();
            if (type == null) continue;
            if (!visited.Add(type)) continue;

            if (type is ITypeParameterSymbol) continue; // Skip unbound generics like T

            if (type.TypeKind == TypeKind.Array && type is IArrayTypeSymbol arrayType)
            {
                // Force native MessagePack ByteArrayFormatter resolution instead of generic Arrays 
                // preventing MessagePackSerializationException when translating raw crypto arrays natively!
                if (arrayType.ElementType.SpecialType == SpecialType.System_Byte) continue;

                collectionTypes.Add(arrayType);
                queue.Enqueue(arrayType.ElementType);
                continue;
            }

            if (type.SpecialType != SpecialType.None) continue; // Primitive/String/Object
            if (type.TypeKind == TypeKind.Enum) continue;

            if (type is INamedTypeSymbol namedType)
            {
                if (namedType.IsUnboundGenericType || namedType.TypeArguments.Any(t => t.TypeKind == TypeKind.TypeParameter))
                {
                    continue; // Skip open generic bounds entirely
                }

                var originalDef = namedType.OriginalDefinition.ToDisplayString(DefinitionFormat);
                
                // Exclude system basics
                if (originalDef == "System.Object" || originalDef == "System.ValueType") continue;

                if (namedType.IsGenericType)
                {
                    if (originalDef.StartsWith("System.Collections.") || originalDef.StartsWith("System.Linq."))
                    {
                        collectionTypes.Add(namedType);
                        foreach (var arg in namedType.TypeArguments) queue.Enqueue(arg);
                        continue;
                    }
                    if (originalDef == "System.Nullable<T>")
                    {
                        collectionTypes.Add(namedType);
                        queue.Enqueue(namedType.TypeArguments[0]);
                        continue;
                    }
                    if (originalDef == "System.Collections.Generic.KeyValuePair<TKey, TValue>")
                    {
                        collectionTypes.Add(namedType);
                        foreach (var arg in namedType.TypeArguments) queue.Enqueue(arg);
                        continue;
                    }

                    // Enqueue generic arguments for any other generic type to ensure deep traversal
                    foreach (var arg in namedType.TypeArguments) queue.Enqueue(arg);
                }

                // Exclude types that natively define their own MessagePack formatters avoiding explicit MsgPack009 collisions
                var hasMessagePackFormatter = namedType.GetAttributes().Any(a => a.AttributeClass?.Name.Contains("MessagePackFormatter") == true || a.AttributeClass?.Name.Contains("MessagePackObject") == true) || 
                                              namedType.OriginalDefinition.GetAttributes().Any(a => a.AttributeClass?.Name.Contains("MessagePackFormatter") == true || a.AttributeClass?.Name.Contains("MessagePackObject") == true);

                if (namedType.TypeKind == TypeKind.Class || namedType.TypeKind == TypeKind.Struct || namedType.TypeKind == TypeKind.Interface)
                {
                    if (namedType.ContainingNamespace.ToDisplayString().StartsWith("System")) continue;

                    if (!hasMessagePackFormatter)
                    {
                        customTypes.Add(namedType);
                    }

                    // Inspect for STJ polymorphic derived types to ensure AOT serializers are generated for all explicit subclasses
                    var derivedAttributes = namedType.GetAttributes().Where(a => 
                        a.AttributeClass?.Name == "JsonDerivedTypeAttribute" || 
                        a.AttributeClass?.ToDisplayString().Contains("JsonDerivedTypeAttribute") == true);

                    foreach (var attr in derivedAttributes)
                    {
                        if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is ITypeSymbol derivedType)
                        {
                            queue.Enqueue(derivedType);
                        }
                    }

                    // Traverse full inheritance hierarchy capturing explicitly implemented base properties missing from struct bounds natively
                    var allMembers = new List<ISymbol>();
                    var currentType = namedType;
                    while (currentType != null && currentType.SpecialType != SpecialType.System_Object)
                    {
                        allMembers.AddRange(currentType.GetMembers());
                        currentType = currentType.BaseType;
                    }

                    var properties = allMembers.OfType<IPropertySymbol>()
                        .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic);
                    
                    foreach (var prop in properties) queue.Enqueue(prop.Type);

                    if (namedType.TypeKind != TypeKind.Interface)
                    {
                        var ctor = namedType.Constructors.OrderByDescending(c => c.Parameters.Length).FirstOrDefault();
                        if (ctor != null)
                        {
                            foreach (var param in ctor.Parameters) queue.Enqueue(param.Type);
                        }
                    }
                }
            }
        }
    }

    private static void GenerateResolver(SourceProductionContext context, HashSet<INamedTypeSymbol> customTypes, HashSet<ITypeSymbol> collectionTypes, string resolverName)
    {
        var uniqueCollectionTypes = collectionTypes
            .GroupBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .ToDictionary(g => g.Key, g => g.First());

        var uniqueCustomTypes = customTypes
            .GroupBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .ToDictionary(g => g.Key, g => g.First());

        // Ensure mutually exclusive bounds safely resolving overlapping generic instances cleanly.
        foreach (var key in uniqueCollectionTypes.Keys)
        {
            uniqueCustomTypes.Remove(key);
        }

        var sortedCollections = uniqueCollectionTypes.Values
            .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .ToList();

        var sortedCustoms = uniqueCustomTypes.Values
            .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("#pragma warning disable MsgPack009");
        sb.AppendLine("using System;");
        sb.AppendLine("using MessagePack;");
        sb.AppendLine("using MessagePack.Formatters;");
        sb.AppendLine();
        sb.AppendLine("namespace Ama.Enterprise.CRDT.MessagePack.Formatters");
        sb.AppendLine("{");
        
        sb.AppendLine($"    public sealed class {resolverName} : global::MessagePack.IFormatterResolver");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static readonly global::MessagePack.IFormatterResolver Instance = new {resolverName}();");
        sb.AppendLine();
        sb.AppendLine($"        private {resolverName}() {{}}");
        sb.AppendLine();
        sb.AppendLine("        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()");
        sb.AppendLine("        {");
        sb.AppendLine("            return FormatterCache<T>.Formatter;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public interface ICustomFormatter<TArg>");
        sb.AppendLine("        {");
        sb.AppendLine("            void Serialize(ref global::MessagePack.MessagePackWriter writer, TArg value, global::MessagePack.MessagePackSerializerOptions options);");
        sb.AppendLine("            TArg Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public sealed class CustomFormatterWrapper<TArg> : global::MessagePack.Formatters.IMessagePackFormatter<TArg>");
        sb.AppendLine("        {");
        sb.AppendLine("            private readonly ICustomFormatter<TArg> _inner;");
        sb.AppendLine("            public CustomFormatterWrapper(ICustomFormatter<TArg> inner) { _inner = inner; }");
        sb.AppendLine("            public void Serialize(ref global::MessagePack.MessagePackWriter writer, TArg value, global::MessagePack.MessagePackSerializerOptions options) => _inner.Serialize(ref writer, value, options);");
        sb.AppendLine("            public TArg Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options) => _inner.Deserialize(ref reader, options);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        private static class FormatterCache<T>");
        sb.AppendLine("        {");
        sb.AppendLine("            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;");
        sb.AppendLine("            static FormatterCache()");
        sb.AppendLine("            {");
        sb.AppendLine("                object formatter = null;");
        sb.AppendLine("                var type = typeof(T);");

        foreach (var type in sortedCollections)
        {
            var typeFullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var instantiation = GetFormatterInstantiation(type);
            if (instantiation != null)
            {
                sb.AppendLine($"                if (type == typeof({typeFullName})) formatter = {instantiation};");
            }
        }

        foreach (var type in sortedCustoms)
        {
            var typeFullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            
            var hasJsonDerived = type.GetAttributes().Any(a => 
                a.AttributeClass?.Name == "JsonDerivedTypeAttribute" || 
                a.AttributeClass?.ToDisplayString().Contains("JsonDerivedTypeAttribute") == true);
            
            if ((type.TypeKind == TypeKind.Interface || type.IsAbstract) && !hasJsonDerived)
            {
                sb.AppendLine($"                if (type == typeof({typeFullName})) formatter = new global::Ama.Enterprise.CRDT.MessagePack.Formatters.CrdtPolymorphicMessagePackFormatter<{typeFullName}>();");
            }
            else
            {
                var formatterName = GetFormatterClassName(type);
                sb.AppendLine($"                if (type == typeof({typeFullName})) formatter = new CustomFormatterWrapper<{typeFullName}>(new {formatterName}());");
            }
        }

        sb.AppendLine("                Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)formatter;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        
        sb.AppendLine();
        sb.AppendLine($"    public static class {resolverName}PolymorphicInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");

        foreach (var type in sortedCollections)
        {
            var typeFullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            global::Ama.Enterprise.CRDT.MessagePack.Formatters.CrdtPolymorphicMessagePackRegistry.Register<{typeFullName}>();");
        }

        foreach (var type in sortedCustoms)
        {
            var typeFullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            
            if (type.TypeKind != TypeKind.Interface && !type.IsAbstract)
            {
                sb.AppendLine($"            global::Ama.Enterprise.CRDT.MessagePack.Formatters.CrdtPolymorphicMessagePackRegistry.Register<{typeFullName}>();");
            }
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");

        foreach (var type in sortedCustoms)
        {
            var hasJsonDerived = type.GetAttributes().Any(a => 
                a.AttributeClass?.Name == "JsonDerivedTypeAttribute" || 
                a.AttributeClass?.ToDisplayString().Contains("JsonDerivedTypeAttribute") == true);

            if ((type.TypeKind == TypeKind.Interface || type.IsAbstract) && !hasJsonDerived) continue;
            
            GenerateFormatter(sb, type, resolverName);
        }

        sb.AppendLine("}");

        context.AddSource($"{resolverName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetFormatterClassName(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", "")
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(", ", "_")
            .Replace(",", "_")
            .Replace(" ", "")
            .Replace("[]", "Array") + "Formatter";
    }

    private static string GetFormatterInstantiation(ITypeSymbol type)
    {
        if (type.TypeKind == TypeKind.Array && type is IArrayTypeSymbol arrType)
        {
            var elemName = arrType.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return $"new global::MessagePack.Formatters.ArrayFormatter<{elemName}>()";
        }
        
        if (type is INamedTypeSymbol named && named.IsGenericType)
        {
            var originalDef = named.OriginalDefinition.ToDisplayString(DefinitionFormat);
            var arg0 = named.TypeArguments.Length > 0 ? named.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) : "";
            var arg1 = named.TypeArguments.Length > 1 ? named.TypeArguments[1].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) : "";
            
            switch (originalDef)
            {
                case "System.Collections.Generic.List<T>":
                    return $"new global::MessagePack.Formatters.ListFormatter<{arg0}>()";
                case "System.Collections.Generic.IList<T>":
                    return $"new global::MessagePack.Formatters.InterfaceListFormatter<{arg0}>()";
                case "System.Collections.Generic.IReadOnlyList<T>":
                    return $"new global::MessagePack.Formatters.InterfaceReadOnlyListFormatter<{arg0}>()";
                case "System.Collections.Generic.IEnumerable<T>":
                    return $"new global::MessagePack.Formatters.InterfaceEnumerableFormatter<{arg0}>()";
                case "System.Collections.Generic.ICollection<T>":
                    return $"new global::MessagePack.Formatters.InterfaceCollectionFormatter<{arg0}>()";
                case "System.Collections.Generic.IReadOnlyCollection<T>":
                    return $"new global::MessagePack.Formatters.InterfaceReadOnlyCollectionFormatter<{arg0}>()";
                case "System.Collections.Generic.Dictionary<TKey, TValue>":
                    return $"new global::MessagePack.Formatters.DictionaryFormatter<{arg0}, {arg1}>()";
                case "System.Collections.Generic.IDictionary<TKey, TValue>":
                    return $"new global::MessagePack.Formatters.InterfaceDictionaryFormatter<{arg0}, {arg1}>()";
                case "System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>":
                    return $"new global::MessagePack.Formatters.InterfaceReadOnlyDictionaryFormatter<{arg0}, {arg1}>()";
                case "System.Collections.Generic.HashSet<T>":
                    return $"new global::MessagePack.Formatters.HashSetFormatter<{arg0}>()";
                case "System.Collections.Generic.ISet<T>":
                    return $"new global::MessagePack.Formatters.InterfaceSetFormatter<{arg0}>()";
                case "System.Collections.Generic.IReadOnlySet<T>":
                    return $"new global::MessagePack.Formatters.InterfaceReadOnlySetFormatter<{arg0}>()";
                case "System.Collections.Generic.KeyValuePair<TKey, TValue>":
                    return $"new global::MessagePack.Formatters.KeyValuePairFormatter<{arg0}, {arg1}>()";
                case "System.Nullable<T>":
                    return $"new global::MessagePack.Formatters.NullableFormatter<{arg0}>()";
            }
        }
        return null;
    }

    private static void GenerateFormatter(StringBuilder sb, INamedTypeSymbol typeSymbol, string resolverName)
    {
        var derivedAttributes = typeSymbol.GetAttributes().Where(a => 
            a.AttributeClass?.Name == "JsonDerivedTypeAttribute" || 
            a.AttributeClass?.ToDisplayString().Contains("JsonDerivedTypeAttribute") == true).ToList();

        if (derivedAttributes.Count > 0)
        {
            GeneratePolymorphicFormatter(sb, typeSymbol, derivedAttributes, resolverName);
            return;
        }

        var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var formatterName = GetFormatterClassName(typeSymbol);

        sb.AppendLine();
        sb.AppendLine($"    public sealed class {formatterName} : {resolverName}.ICustomFormatter<{typeFullName}>");
        sb.AppendLine("    {");

        var ctor = typeSymbol.Constructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();

        if (ctor == null && typeSymbol.TypeKind != TypeKind.Struct)
        {
            sb.AppendLine($"        public void Serialize(ref global::MessagePack.MessagePackWriter writer, {typeFullName} value, global::MessagePack.MessagePackSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine($"            throw new global::System.NotSupportedException(\"Cannot directly serialize parameterless type {typeFullName} missing a public constructor.\");");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public {typeFullName} Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine($"            throw new global::System.NotSupportedException(\"Cannot directly deserialize parameterless type {typeFullName} missing a public constructor.\");");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            return;
        }

        var members = new List<SerializedMember>();
        var mappedProps = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        if (ctor != null)
        {
            for (int i = 0; i < ctor.Parameters.Length; i++)
            {
                var param = ctor.Parameters[i];
                var propName = GetMatchingPropertyName(typeSymbol, param.Name);
                mappedProps.Add(propName);

                var defValue = "default";
                if (param.HasExplicitDefaultValue)
                {
                    defValue = param.ExplicitDefaultValue == null ? "default" : param.ExplicitDefaultValue.ToString();
                    if (param.ExplicitDefaultValue is string) defValue = $"\"{defValue}\"";
                    else if (param.ExplicitDefaultValue is bool b) defValue = b ? "true" : "false";
                }

                members.Add(new SerializedMember
                {
                    Name = param.Name,
                    PropName = propName,
                    Type = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    IsCtor = true,
                    CtorIndex = i,
                    HasDefault = param.HasExplicitDefaultValue,
                    DefaultValue = defValue,
                    Index = members.Count
                });
            }
        }

        // Aggregate entire inheritance tree correctly intercepting base records/classes implicitly avoiding truncation boundaries natively.
        var allMembers = new List<ISymbol>();
        var currentType = typeSymbol;
        while (currentType != null && currentType.SpecialType != SpecialType.System_Object)
        {
            allMembers.AddRange(currentType.GetMembers());
            currentType = currentType.BaseType;
        }

        var properties = allMembers.OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && p.GetMethod != null && p.SetMethod != null)
            .OrderBy(p => p.Name);

        foreach (var prop in properties)
        {
            if (!mappedProps.Contains(prop.Name))
            {
                members.Add(new SerializedMember
                {
                    Name = prop.Name,
                    PropName = prop.Name,
                    Type = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    IsCtor = false,
                    CtorIndex = -1,
                    HasDefault = false,
                    DefaultValue = "default",
                    Index = members.Count
                });
            }
        }

        // Serialize
        sb.AppendLine($"        public void Serialize(ref global::MessagePack.MessagePackWriter writer, {typeFullName} value, global::MessagePack.MessagePackSerializerOptions options)");
        sb.AppendLine("        {");
        if (!typeSymbol.IsValueType)
        {
            sb.AppendLine("            if (value == null) { writer.WriteNil(); return; }");
        }
        sb.AppendLine($"            writer.WriteArrayHeader({members.Count});");

        foreach (var member in members)
        {
            sb.AppendLine($"            options.Resolver.GetFormatterWithVerify<{member.Type}>().Serialize(ref writer, value.{member.PropName}, options);");
        }
        sb.AppendLine("        }");

        // Deserialize
        sb.AppendLine();
        sb.AppendLine($"        public {typeFullName} Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (reader.TryReadNil()) return default;");
        sb.AppendLine("            var count = reader.ReadArrayHeader();");

        for (int i = 0; i < members.Count; i++)
        {
            var member = members[i];
            var varName = $"p{i}";

            sb.AppendLine($"            {member.Type} {varName} = default;");

            if (member.HasDefault)
            {
                sb.AppendLine($"            if (count <= {i}) {varName} = {member.DefaultValue};");
            }

            sb.AppendLine($"            if (count > {i}) {varName} = options.Resolver.GetFormatterWithVerify<{member.Type}>().Deserialize(ref reader, options);");
        }

        sb.AppendLine($"            for (int i = {members.Count}; i < count; i++) reader.Skip();");

        var ctorArgs = string.Join(", ", members.Where(m => m.IsCtor).OrderBy(m => m.CtorIndex).Select(m => $"p{m.Index}"));

        var propSetters = members.Where(m => !m.IsCtor).Select(m => $"{m.PropName} = p{m.Index}").ToList();
        var objectInitializer = propSetters.Count > 0 ? $" {{ {string.Join(", ", propSetters)} }}" : "";

        sb.AppendLine($"            return new {typeFullName}({ctorArgs}){objectInitializer};");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
    }

    private static void GeneratePolymorphicFormatter(StringBuilder sb, INamedTypeSymbol typeSymbol, List<AttributeData> derivedAttributes, string resolverName)
    {
        var typeFullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var formatterName = GetFormatterClassName(typeSymbol);

        sb.AppendLine();
        sb.AppendLine($"    public sealed class {formatterName} : {resolverName}.ICustomFormatter<{typeFullName}>");
        sb.AppendLine("    {");
        
        // Serialize
        sb.AppendLine($"        public void Serialize(ref global::MessagePack.MessagePackWriter writer, {typeFullName} value, global::MessagePack.MessagePackSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value == null) { writer.WriteNil(); return; }");
        sb.AppendLine("            var type = value.GetType();");
        sb.AppendLine("            writer.WriteArrayHeader(2);");
        
        foreach (var attr in derivedAttributes)
        {
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is ITypeSymbol derivedType)
            {
                string discriminator = derivedType.Name;
                if (attr.ConstructorArguments.Length > 1 && attr.ConstructorArguments[1].Value != null)
                {
                    discriminator = attr.ConstructorArguments[1].Value.ToString();
                }
                var derivedFullName = derivedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                
                sb.AppendLine($"            if (type == typeof({derivedFullName}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                writer.Write(\"{discriminator}\");");
                sb.AppendLine($"                options.Resolver.GetFormatterWithVerify<{derivedFullName}>().Serialize(ref writer, ({derivedFullName})value, options);");
                sb.AppendLine("                return;");
                sb.AppendLine("            }");
            }
        }
        sb.AppendLine($"            throw new global::System.NotSupportedException($\"Type '{{type}}' is not registered as a derived polymorphic type of {typeFullName}.\");");
        sb.AppendLine("        }");

        // Deserialize
        sb.AppendLine();
        sb.AppendLine($"        public {typeFullName} Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (reader.TryReadNil()) return default;");
        sb.AppendLine("            var count = reader.ReadArrayHeader();");
        sb.AppendLine("            if (count != 2) throw new global::MessagePack.MessagePackSerializationException(\"Invalid polymorphic MessagePack array length.\");");
        sb.AppendLine("            var discriminator = reader.ReadString();");
        
        foreach (var attr in derivedAttributes)
        {
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is ITypeSymbol derivedType)
            {
                string discriminator = derivedType.Name;
                if (attr.ConstructorArguments.Length > 1 && attr.ConstructorArguments[1].Value != null)
                {
                    discriminator = attr.ConstructorArguments[1].Value.ToString();
                }
                var derivedFullName = derivedType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                
                sb.AppendLine($"            if (discriminator == \"{discriminator}\")");
                sb.AppendLine("            {");
                sb.AppendLine($"                var result = options.Resolver.GetFormatterWithVerify<{derivedFullName}>().Deserialize(ref reader, options);");
                sb.AppendLine($"                return ({typeFullName})result;");
                sb.AppendLine("            }");
            }
        }
        
        sb.AppendLine($"            throw new global::System.NotSupportedException($\"Discriminator '{{discriminator}}' is not registered for {typeFullName}.\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string GetMatchingPropertyName(INamedTypeSymbol typeSymbol, string paramName)
    {
        var allMembers = new List<ISymbol>();
        var current = typeSymbol;
        while (current != null && current.SpecialType != SpecialType.System_Object)
        {
            allMembers.AddRange(current.GetMembers());
            current = current.BaseType;
        }

        var properties = allMembers.OfType<IPropertySymbol>();
        var match = properties.FirstOrDefault(p => p.Name.Equals(paramName, StringComparison.OrdinalIgnoreCase));
        return match != null ? match.Name : paramName;
    }

    private sealed class SerializedMember
    {
        public string Name { get; set; }
        public string PropName { get; set; }
        public string Type { get; set; }
        public bool IsCtor { get; set; }
        public int CtorIndex { get; set; }
        public bool HasDefault { get; set; }
        public string DefaultValue { get; set; }
        public int Index { get; set; }
    }
}