namespace Ama.Enterprise.P2p.WebRTC.Services;

using System;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Provides mechanisms to generate and accept WebRTC connection invitations via SDP exchange.
/// This enables out-of-band discovery like QR codes or Table Storage signaling.
/// </summary>
public interface IWebRtcInvitationService
{
    /// <summary>
    /// Creates an invitation (SDP Offer) to be shared with another peer.
    /// </summary>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task returning the tracking connection ID and the generated SDP offer string.</returns>
    Task<(Guid ConnectionId, string SdpOffer)> CreateInvitationAsync(CancellationToken cancellationToken);

    /// <summary>
    /// Accepts an invitation (SDP Offer) generated by another node and produces a corresponding answer (SDP Answer).
    /// </summary>
    /// <param name="sdpOffer">The received SDP offer string.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task returning the new localized connection ID and the SDP answer string to send back.</returns>
    Task<(Guid ConnectionId, string SdpAnswer)> AcceptInvitationAsync(string sdpOffer, CancellationToken cancellationToken);

    /// <summary>
    /// Finalizes the connection by applying the received SDP answer to the local tracked offer.
    /// </summary>
    /// <param name="connectionId">The connection ID created during CreateInvitationAsync.</param>
    /// <param name="sdpAnswer">The received SDP answer from the remote peer.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task FinalizeInvitationAsync(Guid connectionId, string sdpAnswer, CancellationToken cancellationToken);
}