<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="MessagePack" Version="3.1.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ama.Enterprise.CRDT\Ama.Enterprise.CRDT.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ama.Enterprise.Project.Analyzers\Ama.Enterprise.Project.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
