namespace Ama.Enterprise.CRDT.MessagePack.Analyzers.UnitTests;

using System;
using System.Linq;
using System.Reflection;
using System.Text.Json.Serialization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Shouldly;
using Xunit;

public sealed class MessagePackFormatterGeneratorTests
{
    private const string MessagePackStubs = @"
// Stubs to allow the generated test code to compile successfully without bringing in full MessagePack dependencies
namespace MessagePack
{
    public interface IFormatterResolver { IMessagePackFormatter<T> GetFormatterWithVerify<T>(); }
    public class MessagePackSerializerOptions { public IFormatterResolver Resolver { get; } }
    public struct MessagePackWriter { public void WriteNil() {} public void WriteArrayHeader(int count) {} }
    public struct MessagePackReader { public bool TryReadNil() => false; public int ReadArrayHeader() => 0; public void Skip() {} }
    
    namespace Formatters
    {
        public interface IMessagePackFormatter<T> { 
            void Serialize(ref MessagePackWriter w, T v, MessagePackSerializerOptions o);
            T Deserialize(ref MessagePackReader r, MessagePackSerializerOptions o);
        }
        public class ListFormatter<T> : IMessagePackFormatter<System.Collections.Generic.List<T>> { 
            public void Serialize(ref MessagePackWriter w, System.Collections.Generic.List<T> v, MessagePackSerializerOptions o) {} 
            public System.Collections.Generic.List<T> Deserialize(ref MessagePackReader r, MessagePackSerializerOptions o) => null;
        }
        public class DictionaryFormatter<K,V> : IMessagePackFormatter<System.Collections.Generic.Dictionary<K,V>> {
            public void Serialize(ref MessagePackWriter w, System.Collections.Generic.Dictionary<K,V> v, MessagePackSerializerOptions o) {} 
            public System.Collections.Generic.Dictionary<K,V> Deserialize(ref MessagePackReader r, MessagePackSerializerOptions o) => null;
        }
        public class NullableFormatter<T> : IMessagePackFormatter<System.Nullable<T>> where T : struct {
            public void Serialize(ref MessagePackWriter w, System.Nullable<T> v, MessagePackSerializerOptions o) {} 
            public System.Nullable<T> Deserialize(ref MessagePackReader r, MessagePackSerializerOptions o) => default;
        }
        public class ArrayFormatter<T> : IMessagePackFormatter<T[]> {
            public void Serialize(ref MessagePackWriter w, T[] v, MessagePackSerializerOptions o) {} 
            public T[] Deserialize(ref MessagePackReader r, MessagePackSerializerOptions o) => null;
        }
        public class HashSetFormatter<T> : IMessagePackFormatter<System.Collections.Generic.HashSet<T>> {
            public void Serialize(ref MessagePackWriter w, System.Collections.Generic.HashSet<T> v, MessagePackSerializerOptions o) {} 
            public System.Collections.Generic.HashSet<T> Deserialize(ref MessagePackReader r, MessagePackSerializerOptions o) => null;
        }
        public class InterfaceListFormatter<T> : IMessagePackFormatter<System.Collections.Generic.IReadOnlyList<T>> {
            public void Serialize(ref MessagePackWriter w, System.Collections.Generic.IReadOnlyList<T> v, MessagePackSerializerOptions o) {} 
            public System.Collections.Generic.IReadOnlyList<T> Deserialize(ref MessagePackReader r, MessagePackSerializerOptions o) => null;
        }
        public class InterfaceSetFormatter<T> : IMessagePackFormatter<System.Collections.Generic.ISet<T>> {
            public void Serialize(ref MessagePackWriter w, System.Collections.Generic.ISet<T> v, MessagePackSerializerOptions o) {} 
            public System.Collections.Generic.ISet<T> Deserialize(ref MessagePackReader r, MessagePackSerializerOptions o) => null;
        }
    }
}
";

    [Fact]
    public void WhenJsonSerializableIsApplied_ShouldGenerateFormattersAndTraverseProperties()
    {
        var source = @"
using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace TestNamespace
{
    public record MyModel(string Name, List<int> Values, Dictionary<string, MyChildModel> Children);

    public record MyChildModel(int Id);

    [JsonSerializable(typeof(MyModel))]
    public partial class TestJsonContext : JsonSerializerContext
    {
    }
}
" + MessagePackStubs;

        var expectedGeneratedCode = @"// <auto-generated/>
using System;
using MessagePack;
using MessagePack.Formatters;

namespace Ama.Enterprise.CRDT.MessagePack.Formatters
{
    public sealed class SourceGeneratorTests_MessagePackResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new SourceGeneratorTests_MessagePackResolver();

        private SourceGeneratorTests_MessagePackResolver() {}

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;
            static FormatterCache()
            {
                object formatter = null;
                var type = typeof(T);
                if (type == typeof(global::System.Collections.Generic.List<int>)) formatter = new global::MessagePack.Formatters.ListFormatter<int>();
                if (type == typeof(global::System.Collections.Generic.Dictionary<string, global::TestNamespace.MyChildModel>)) formatter = new global::MessagePack.Formatters.DictionaryFormatter<string, global::TestNamespace.MyChildModel>();
                if (type == typeof(global::TestNamespace.MyModel)) formatter = new TestNamespace_MyModelFormatter();
                if (type == typeof(global::TestNamespace.MyChildModel)) formatter = new TestNamespace_MyChildModelFormatter();
                Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)formatter;
            }
        }
    }

    public sealed class TestNamespace_MyModelFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::TestNamespace.MyModel>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::TestNamespace.MyModel value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null) { writer.WriteNil(); return; }
            writer.WriteArrayHeader(3);
            options.Resolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Name, options);
            options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.List<int>>().Serialize(ref writer, value.Values, options);
            options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<string, global::TestNamespace.MyChildModel>>().Serialize(ref writer, value.Children, options);
        }

        public global::TestNamespace.MyModel Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil()) return default;
            var count = reader.ReadArrayHeader();
            string p0 = default;
            if (count > 0) p0 = options.Resolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
            global::System.Collections.Generic.List<int> p1 = default;
            if (count > 1) p1 = options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.List<int>>().Deserialize(ref reader, options);
            global::System.Collections.Generic.Dictionary<string, global::TestNamespace.MyChildModel> p2 = default;
            if (count > 2) p2 = options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.Dictionary<string, global::TestNamespace.MyChildModel>>().Deserialize(ref reader, options);
            for (int i = 3; i < count; i++) reader.Skip();
            return new global::TestNamespace.MyModel(p0, p1, p2);
        }
    }

    public sealed class TestNamespace_MyChildModelFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::TestNamespace.MyChildModel>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::TestNamespace.MyChildModel value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null) { writer.WriteNil(); return; }
            writer.WriteArrayHeader(1);
            options.Resolver.GetFormatterWithVerify<int>().Serialize(ref writer, value.Id, options);
        }

        public global::TestNamespace.MyChildModel Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil()) return default;
            var count = reader.ReadArrayHeader();
            int p0 = default;
            if (count > 0) p0 = options.Resolver.GetFormatterWithVerify<int>().Deserialize(ref reader, options);
            for (int i = 1; i < count; i++) reader.Skip();
            return new global::TestNamespace.MyChildModel(p0);
        }
    }
}
";

        RunGeneratorAndAssertOutput(source, expectedGeneratedCode);
    }

    [Fact]
    public void WhenTypeIsStruct_ShouldOmitNullCheck()
    {
        var source = @"
using System.Text.Json.Serialization;

namespace TestNamespace
{
    public struct MyStruct
    {
        public int? Id { get; }
        public MyStruct(int? id) { Id = id; }
    }

    [JsonSerializable(typeof(MyStruct))]
    public partial class TestJsonContext : JsonSerializerContext { }
}
" + MessagePackStubs;

        var expectedCode = @"// <auto-generated/>
using System;
using MessagePack;
using MessagePack.Formatters;

namespace Ama.Enterprise.CRDT.MessagePack.Formatters
{
    public sealed class SourceGeneratorTests_MessagePackResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new SourceGeneratorTests_MessagePackResolver();

        private SourceGeneratorTests_MessagePackResolver() {}

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;
            static FormatterCache()
            {
                object formatter = null;
                var type = typeof(T);
                if (type == typeof(int?)) formatter = new global::MessagePack.Formatters.NullableFormatter<int>();
                if (type == typeof(global::TestNamespace.MyStruct)) formatter = new TestNamespace_MyStructFormatter();
                Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)formatter;
            }
        }
    }

    public sealed class TestNamespace_MyStructFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::TestNamespace.MyStruct>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::TestNamespace.MyStruct value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.WriteArrayHeader(1);
            options.Resolver.GetFormatterWithVerify<int?>().Serialize(ref writer, value.Id, options);
        }

        public global::TestNamespace.MyStruct Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil()) return default;
            var count = reader.ReadArrayHeader();
            int? p0 = default;
            if (count > 0) p0 = options.Resolver.GetFormatterWithVerify<int?>().Deserialize(ref reader, options);
            for (int i = 1; i < count; i++) reader.Skip();
            return new global::TestNamespace.MyStruct(p0);
        }
    }
}";

        RunGeneratorAndAssertOutput(source, expectedCode);
    }

    [Fact]
    public void WhenConstructorHasDefaultValues_ShouldGenerateFallbackAssignments()
    {
        var source = @"
using System.Text.Json.Serialization;

namespace TestNamespace
{
    public record ModelWithDefaults(string Text = ""Fallback"", bool IsActive = true, int Number = 42);

    [JsonSerializable(typeof(ModelWithDefaults))]
    public partial class TestJsonContext : JsonSerializerContext { }
}
" + MessagePackStubs;

        var expectedCode = @"// <auto-generated/>
using System;
using MessagePack;
using MessagePack.Formatters;

namespace Ama.Enterprise.CRDT.MessagePack.Formatters
{
    public sealed class SourceGeneratorTests_MessagePackResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new SourceGeneratorTests_MessagePackResolver();

        private SourceGeneratorTests_MessagePackResolver() {}

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;
            static FormatterCache()
            {
                object formatter = null;
                var type = typeof(T);
                if (type == typeof(global::TestNamespace.ModelWithDefaults)) formatter = new TestNamespace_ModelWithDefaultsFormatter();
                Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)formatter;
            }
        }
    }

    public sealed class TestNamespace_ModelWithDefaultsFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::TestNamespace.ModelWithDefaults>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::TestNamespace.ModelWithDefaults value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null) { writer.WriteNil(); return; }
            writer.WriteArrayHeader(3);
            options.Resolver.GetFormatterWithVerify<string>().Serialize(ref writer, value.Text, options);
            options.Resolver.GetFormatterWithVerify<bool>().Serialize(ref writer, value.IsActive, options);
            options.Resolver.GetFormatterWithVerify<int>().Serialize(ref writer, value.Number, options);
        }

        public global::TestNamespace.ModelWithDefaults Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil()) return default;
            var count = reader.ReadArrayHeader();
            string p0 = default;
            if (count <= 0) p0 = ""Fallback"";
            if (count > 0) p0 = options.Resolver.GetFormatterWithVerify<string>().Deserialize(ref reader, options);
            bool p1 = default;
            if (count <= 1) p1 = true;
            if (count > 1) p1 = options.Resolver.GetFormatterWithVerify<bool>().Deserialize(ref reader, options);
            int p2 = default;
            if (count <= 2) p2 = 42;
            if (count > 2) p2 = options.Resolver.GetFormatterWithVerify<int>().Deserialize(ref reader, options);
            for (int i = 3; i < count; i++) reader.Skip();
            return new global::TestNamespace.ModelWithDefaults(p0, p1, p2);
        }
    }
}";

        RunGeneratorAndAssertOutput(source, expectedCode);
    }

    [Fact]
    public void WhenGeneratingForCollectionsAndArrays_ShouldMapCorrectFormatters()
    {
        var source = @"
using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace TestNamespace
{
    public record CollectionsModel(int[] ArrayData, HashSet<string> SetData, IReadOnlyList<long> ListData, ISet<bool> InterfaceSetData);

    [JsonSerializable(typeof(CollectionsModel))]
    public partial class TestJsonContext : JsonSerializerContext { }
}
" + MessagePackStubs;

        var expectedCode = @"// <auto-generated/>
using System;
using MessagePack;
using MessagePack.Formatters;

namespace Ama.Enterprise.CRDT.MessagePack.Formatters
{
    public sealed class SourceGeneratorTests_MessagePackResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new SourceGeneratorTests_MessagePackResolver();

        private SourceGeneratorTests_MessagePackResolver() {}

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;
            static FormatterCache()
            {
                object formatter = null;
                var type = typeof(T);
                if (type == typeof(int[])) formatter = new global::MessagePack.Formatters.ArrayFormatter<int>();
                if (type == typeof(global::System.Collections.Generic.HashSet<string>)) formatter = new global::MessagePack.Formatters.HashSetFormatter<string>();
                if (type == typeof(global::System.Collections.Generic.IReadOnlyList<long>)) formatter = new global::MessagePack.Formatters.InterfaceListFormatter<long>();
                if (type == typeof(global::System.Collections.Generic.ISet<bool>)) formatter = new global::MessagePack.Formatters.InterfaceSetFormatter<bool>();
                if (type == typeof(global::TestNamespace.CollectionsModel)) formatter = new TestNamespace_CollectionsModelFormatter();
                Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)formatter;
            }
        }
    }

    public sealed class TestNamespace_CollectionsModelFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::TestNamespace.CollectionsModel>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::TestNamespace.CollectionsModel value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null) { writer.WriteNil(); return; }
            writer.WriteArrayHeader(4);
            options.Resolver.GetFormatterWithVerify<int[]>().Serialize(ref writer, value.ArrayData, options);
            options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.HashSet<string>>().Serialize(ref writer, value.SetData, options);
            options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.IReadOnlyList<long>>().Serialize(ref writer, value.ListData, options);
            options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.ISet<bool>>().Serialize(ref writer, value.InterfaceSetData, options);
        }

        public global::TestNamespace.CollectionsModel Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil()) return default;
            var count = reader.ReadArrayHeader();
            int[] p0 = default;
            if (count > 0) p0 = options.Resolver.GetFormatterWithVerify<int[]>().Deserialize(ref reader, options);
            global::System.Collections.Generic.HashSet<string> p1 = default;
            if (count > 1) p1 = options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.HashSet<string>>().Deserialize(ref reader, options);
            global::System.Collections.Generic.IReadOnlyList<long> p2 = default;
            if (count > 2) p2 = options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.IReadOnlyList<long>>().Deserialize(ref reader, options);
            global::System.Collections.Generic.ISet<bool> p3 = default;
            if (count > 3) p3 = options.Resolver.GetFormatterWithVerify<global::System.Collections.Generic.ISet<bool>>().Deserialize(ref reader, options);
            for (int i = 4; i < count; i++) reader.Skip();
            return new global::TestNamespace.CollectionsModel(p0, p1, p2, p3);
        }
    }
}";
        RunGeneratorAndAssertOutput(source, expectedCode);
    }

    [Fact]
    public void WhenTypeHasNoPublicConstructor_ShouldGenerateComment()
    {
        var source = @"
using System.Text.Json.Serialization;

namespace TestNamespace
{
    public class PrivateClass
    {
        private PrivateClass() {}
    }

    [JsonSerializable(typeof(PrivateClass))]
    public partial class TestJsonContext : JsonSerializerContext { }
}
" + MessagePackStubs;

        var expectedCode = @"// <auto-generated/>
using System;
using MessagePack;
using MessagePack.Formatters;

namespace Ama.Enterprise.CRDT.MessagePack.Formatters
{
    public sealed class SourceGeneratorTests_MessagePackResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new SourceGeneratorTests_MessagePackResolver();

        private SourceGeneratorTests_MessagePackResolver() {}

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;
            static FormatterCache()
            {
                object formatter = null;
                var type = typeof(T);
                if (type == typeof(global::TestNamespace.PrivateClass)) formatter = new TestNamespace_PrivateClassFormatter();
                Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)formatter;
            }
        }
    }

    public sealed class TestNamespace_PrivateClassFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::TestNamespace.PrivateClass>
    {
        // No public constructor found for PrivateClass
    }
}";
        RunGeneratorAndAssertOutput(source, expectedCode);
    }

    [Fact]
    public void WhenTypeHasPropertiesAndParameterlessConstructor_ShouldSerializeProperties()
    {
        var source = @"
using System.Text.Json.Serialization;

namespace TestNamespace
{
    public sealed record TreeNode
    {
        public required object Id { get; init; }
        public object Value { get; set; }
        public object ParentId { get; set; }
    }

    [JsonSerializable(typeof(TreeNode))]
    public partial class TestJsonContext : JsonSerializerContext { }
}
" + MessagePackStubs;

        var expectedCode = @"// <auto-generated/>
using System;
using MessagePack;
using MessagePack.Formatters;

namespace Ama.Enterprise.CRDT.MessagePack.Formatters
{
    public sealed class SourceGeneratorTests_MessagePackResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new SourceGeneratorTests_MessagePackResolver();

        private SourceGeneratorTests_MessagePackResolver() {}

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;
            static FormatterCache()
            {
                object formatter = null;
                var type = typeof(T);
                if (type == typeof(global::TestNamespace.TreeNode)) formatter = new TestNamespace_TreeNodeFormatter();
                Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)formatter;
            }
        }
    }

    public sealed class TestNamespace_TreeNodeFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::TestNamespace.TreeNode>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::TestNamespace.TreeNode value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null) { writer.WriteNil(); return; }
            writer.WriteArrayHeader(3);
            options.Resolver.GetFormatterWithVerify<object>().Serialize(ref writer, value.Id, options);
            options.Resolver.GetFormatterWithVerify<object>().Serialize(ref writer, value.ParentId, options);
            options.Resolver.GetFormatterWithVerify<object>().Serialize(ref writer, value.Value, options);
        }

        public global::TestNamespace.TreeNode Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil()) return default;
            var count = reader.ReadArrayHeader();
            object p0 = default;
            if (count > 0) p0 = options.Resolver.GetFormatterWithVerify<object>().Deserialize(ref reader, options);
            object p1 = default;
            if (count > 1) p1 = options.Resolver.GetFormatterWithVerify<object>().Deserialize(ref reader, options);
            object p2 = default;
            if (count > 2) p2 = options.Resolver.GetFormatterWithVerify<object>().Deserialize(ref reader, options);
            for (int i = 3; i < count; i++) reader.Skip();
            return new global::TestNamespace.TreeNode() { Id = p0, ParentId = p1, Value = p2 };
        }
    }
}";
        RunGeneratorAndAssertOutput(source, expectedCode);
    }

    private static void RunGeneratorAndAssertOutput(string source, string expectedGeneratedCode)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source);

        // Explicitly load the JSON serialization attributes just in case
        _ = typeof(JsonSerializableAttribute);

        var references = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .Select(a => MetadataReference.CreateFromFile(a.Location))
            .Cast<MetadataReference>()
            .ToList();

        // Safety fallback ensuring System.Runtime is loaded for testing context resolutions
        var systemRuntime = Assembly.Load("System.Runtime");
        if (references.All(r => r.Display != systemRuntime.Location))
        {
            references.Add(MetadataReference.CreateFromFile(systemRuntime.Location));
        }

        var compilation = CSharpCompilation.Create("SourceGeneratorTests",
            new[] { syntaxTree },
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new Generators.MessagePackFormatterGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);

        driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        diagnostics.ShouldBeEmpty();

        var generatedTrees = outputCompilation.SyntaxTrees.ToList();
        generatedTrees.Count.ShouldBe(2, "Expected the original syntax tree plus one generated syntax tree.");

        var actualGeneratedCode = generatedTrees.Last().ToString();

        // Normalize line endings and trim space for robust cross-OS evaluation comparisons
        var normalizedActual = actualGeneratedCode.Replace("\r\n", "\n").Trim();
        var normalizedExpected = expectedGeneratedCode.Replace("\r\n", "\n").Trim();

        normalizedActual.ShouldBe(normalizedExpected);
    }
}