namespace Ama.Enterprise.P2p.Models.Core;

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

/// <summary>
/// Defines a strict contract for distributed payloads to natively support the Tolerant Reader pattern.
/// By implementing this interface, older network nodes (e.g., running version 1) can receive,
/// preserve, and re-transmit messages generated by newer nodes (e.g., running version 2) without destructive data loss.
/// This ensures forward compatibility across both JSON and Binary (MessagePack) serialization boundaries.
/// </summary>
/// <example>
/// The following example demonstrates how to implement this interface on a custom data transfer object:
/// <code>
/// public sealed record MyCustomMessage : IExtensibleDistributedPayload
/// {
///     public string Id { get; init; } = string.Empty;
///
///     // Ensures unknown JSON properties are captured and re-serialized.
///     [JsonExtensionData]
///     public IDictionary&lt;string, JsonElement&gt;? JsonExtensionData { get; set; }
///
///     // Ensures unknown binary indices are preserved. Must be ignored by System.Text.Json.
///     [JsonIgnore]
///     public IList&lt;ReadOnlyMemory&lt;byte&gt;&gt;? BinaryExtensionData { get; set; }
/// }
/// </code>
/// </example>
public interface IExtensibleDistributedPayload
{
    /// <summary>
    /// Captures unknown Map-based JSON properties natively during <see cref="System.Text.Json"/> deserialization.
    /// The Native AOT serialization engine automatically populates this property when reading unrecognized fields,
    /// and reconstructs them into the payload upon serialization.
    /// </summary>
    [JsonExtensionData]
    IDictionary<string, JsonElement>? JsonExtensionData { get; set; }

    /// <summary>
    /// Captures unknown structural Array-based trailing elements during MessagePack binary deserialization.
    /// The Native AOT generator explicitly unpacks unmapped indices into this list, protecting binary integrity
    /// so that older versions can forward new fields without losing them.
    /// </summary>
    /// <remarks>
    /// Consumers must exclusively append new properties strictly to the end of their DTOs to prevent index shifts.
    /// The <see cref="JsonIgnoreAttribute"/> is required to prevent System.Text.Json from attempting to serialize this binary fallback data.
    /// </remarks>
    [JsonIgnore]
    IList<ReadOnlyMemory<byte>>? BinaryExtensionData { get; set; }
}